local_backend: true
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: local-working # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
